#!/usr/bin/env python

"""make_docs - Make HTML docs for gummworld2/gamelib.
"""

from glob import glob
import os
import sys
import pydoc
import paths
if __name__ == '__main__':

##    help(pydoc)

    # write package index gamelib.html
    sys.path.append('gamelib')
    sys.argv[1:] = ['-w','gamelib']
    pydoc.cli()
    
    # write module docs
    pydoc.writedocs('gamelib', pkgpath='gamelib.')
